services:
  db:
    image: postgres:16-alpine
    container_name: prueba-db
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "8899:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./SCHEMA-CRUD.sql:/docker-entrypoint-initdb.d/schema.sql:ro
    restart: unless-stopped

  api:
    build: .
    container_name: prueba-api
    depends_on:
      db:
        condition: service_healthy
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_NAME: mydb
      DB_USER: postgres
      DB_PASSWORD: postgres
      SERVER_PORT: 9988
    ports:
      - "9988:9988"
    restart: unless-stopped

volumes:
  postgres_data:
